# Generated by Django 4.0 on 2021-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=255, verbose_name=(('owner', 'Owner'),)),
        ),
    ]
